### ISSUE TITLE
RuntimeError: Failed to login with telecomegypt

### ISSUE THREAD

**Issue by mohamed-zezo** [grimpy/ispapi#2]
I'm trying to use telecomegypt client to get my quota, but I get this error:  

> `Traceback (most recent call last):
>   File "/home/mohamed/Documents/test/venv/bin/ispapi", line 33, in <module>
>     sys.exit(load_entry_point('ispapi==0.1', 'console_scripts', 'ispapi')())
>   File "/home/mohamed/Documents/test/venv/lib/python3.6/site-packages/ispapi-0.1-py3.6.egg/ispapi/__main__.py", line 112, in main
>   File "/home/mohamed/Documents/test/venv/lib/python3.6/site-packages/ispapi-0.1-py3.6.egg/ispapi/__main__.py", line 73, in <lambda>
>   File "/home/mohamed/Documents/test/venv/lib/python3.6/site-packages/ispapi-0.1-py3.6.egg/ispapi/__main__.py", line 67, in process
>   File "/home/mohamed/Documents/test/venv/lib/python3.6/site-packages/ispapi-0.1-py3.6.egg/ispapi/providers/provider.py", line 58, in print_quota
>   File "/home/mohamed/Documents/test/venv/lib/python3.6/site-packages/ispapi-0.1-py3.6.egg/ispapi/providers/provider.py", line 29, in login
>   File "/home/mohamed/Documents/test/venv/lib/python3.6/site-packages/ispapi-0.1-py3.6.egg/ispapi/providers/telecomegypt.py", line 72, in _login
>   File "/home/mohamed/Documents/test/venv/lib/python3.6/site-packages/ispapi-0.1-py3.6.egg/ispapi/providers/telecomegypt.py", line 80, in _validate_response
> RuntimeError: Failed to login: Something went wrong
> `  

![Image of error](https://i.imgur.com/YQF6GA5.png)

Any thoughts on why I'm getting this? 

Thank you for sharing this tool.

**Comment by karimawi** [comment]
You have to provide the hashed password, you can get that by using your browser to login while having the network tab in the console open (filter by fetch/xhr requests to make it easier to find) you'll find the login API request listed as `login?channelId=WEB_APP`, click it, go to the payload tab, you'll find the hashed password, this will remain the same as long as you don't change your password, so you'll only do this once, and then you can use the hash with the CLI, I'm currently trying to find how the heck does that password get hashed, there must be a way to get the hash via code instead of manually getting it, I'll let you know if I find something.

![image](https://github.com/grimpy/ispapi/assets/69881381/575e1ab3-726f-49a8-b8df-90752f449808)
